version: '3'

services:

  db:
    image: mysql:8
    container_name: liferay_db
    restart: always
    environment:
      MYSQL_DATABASE: liferay
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USERS: liferay
      MYSQL_PASSWORD: l1f3ray
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  portal:
    image: liferay/portal:7.3.4-ga5
    user: root
    container_name: liferay_portal
    restart: on-failure
    environment:
      LIFERAY_JVM_OPTS: -XX:NewSize=700m -XX:MaxNewSize=700m -Xms2048m -Xmx2048m -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=20 -XX:ParallelGCThreads=8
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://db/liferay?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: root
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: password
      JAVA_VERSION: zulu11
    ports:
      - "8000:8000"
      - "8080:8080"
      - "11311:11311"
    volumes:
      - ./liferay:/mnt/liferay:Z
      - liferay_war:/opt/liferay/osgi/war
    depends_on:
      - db
    links:
      - db

networks:
  default:

volumes:
  db-data: {}
  liferay_war: {}