apiDir: "../api/src/main/java"
apiPackagePath: "com.liferay.sampleVue"
application:
    baseURI: "/sample-vue"
    className: "SampleVueApplication"
    name: "Liferay.SampleVue"
author: "David Brenes"