info:
  description: "Solar Budget API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "Anidia's Solar Budget AI"
  version: v1.0
openapi: 3.0.1

components:
  schemas:
    SolarBudgetRequest:
      description: The required information to calculate a Solar Budget
      properties:
        houseType:
          description: Kind of house
          type: string
          enum: [ Unifamiliar de 1 planta sin A/A, Unifamiliar de 1 planta con A/A, 
          Unifamiliar de 2-3 plantas sin A/A ni piscina, Unifamiliar de 2-3 plantas con A/A o piscina,
          Unifamiliar de 2-3 plantas con A/A y piscina o calefacción eléctrica ]
        monthlyConsumption:
          description: Monthly consumprion
          type: integer 
        annualConsumption: 
          description: Annual Consumption
          type: integer 
        roofType:
          description: Roof type
          type: string 
          enum: ["Plano o inclinación menor a 20º", "Inclinación superior a 20º"]


    SolarBudget:
      description: Information about the solar budget sent by Solusoft API
      properties:
        panelsType:
          description: Tipo de paneles
          type: string
        size:
          description: Size
          $ref: "#/components/schemas/SolarBudgetSize"
        inverter:
          description: Inverter
          $ref: "#/components/schemas/SolarOutputInverter"
        panelsExtra:
          description: Extra panels
          type: string
        triphasicExtra:
          description: Extra triphasic
          type: string
        inverterExtra:
          description: Extra inverter
          type: string
        roofExtra:
          description: Extra roof
          type: string
        pergolaExtra:
          description: Extra pergola
          type: string
        pipelineExtra:
          description: Extra pipeline
          type: string
        carCharger:
          description: Car charger
          type: string
        battery:
          description: Battery
          type: string
        additionalPanelsInstallation:
          description: Additional Installation
          type: string
        totalPrize:
          description: Total prize
          type: string
        superiorInstallation:
          description: Superior installation data
          $ref: "#/components/schemas/SolarSuperiorInstallation"
        

    SolarBudgetSize:
      description: Information about some extra from the solar budget
      properties:
        value:
          description: Detail of the extra
          type: string
        unitPrice:
          description: Unit price for the extra
          type: string
        price:
          description: Price for the extra
          type: string
        basePanels:
          description: Base panels
          type: string
        totalPanels:
          description: Total panels
          type: string

    SolarOutputInverter:
      description: Inverter info
      properties:
        brand:
          description: Brand
          type: string
        model:
          description: Model
          type: string
        price:
          description: Price
          type: string
    
    SuperiorSize:
      properties:
        value:
           type: string
        price:
           type: string
        basePanels:
          description: Base panels
          type: string

    SolarSuperiorInstallation:
      properties:
        superiorSize:
           $ref: "#/components/schemas/SuperiorSize"
        panelType:
          type: string
        inverterType:
          type: string
        extraFornius:
          type: string
        panelsExtra:
          type: string
        triphasicExtra:
          type: string
        inverterExtra:
          type: string
        roofExtra:
          type: string
        pergolaExtra:
          type: string
        pipelineExtra:
          type: string
        carCharger:
          type: string
        battery:
          type: string
        additionalPanelsInstallation:
          type: string
         
paths:
  "/solar-budgets":
    post:
      operationId: postSolarBudget
      summary: Create a Solar Budget using Solusoft API
      description: Converts all the information into a format usable by Solusoft and returns the response
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SolarBudgetRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/SolarBudgetRequest"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SolarBudget"
            application/xml:
              schema:
                $ref: "#/components/schemas/SolarBudget"
          description: The budget has been created